# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version = 1

# Apply Apache-2.0 and copyright to .github/ so REUSE lint passes without per-file headers
[[annotations]]
path = ".github/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "examples/cxrjs/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"
